export const englishTools = [
  {
    slug: "roas-calculator",
    code: "MKT-01",
    category: "Marketing",
    title: "ROAS Calculator",
    short: "Measure return on ad spend and the revenue needed to break even.",
    description: "Free ROAS calculator for paid media. Enter ad spend, revenue and gross margin to calculate ROAS, ad-attributed profit and break-even ROAS in your browser.",
    keywords: ["ROAS calculator", "return on ad spend", "break even ROAS", "advertising ROI"],
    intro: "Turn campaign spend and attributed revenue into a decision-ready ROAS. Add gross margin to see whether a campaign that looks efficient is actually above its break-even point.",
    steps: ["Enter ad spend and attributed revenue.", "Add your gross margin for a break-even check.", "Compare actual ROAS with break-even ROAS before scaling."],
    notes: [
      "ROAS equals attributed revenue divided by ad spend. A 4.0× ROAS means every $1 of media spend generated $4 in attributed revenue.",
      "Revenue is not profit. If your gross margin is 25%, your break-even ROAS is 4.0× before overhead, returns and payment fees. Attribution settings also change the reported revenue, so compare campaigns using the same window and model.",
    ],
    faq: [
      { q: "What is a good ROAS?", a: "There is no universal target. Your break-even point depends on gross margin, fulfilment costs, overhead and the share of sales that would have happened without advertising." },
      { q: "How is break-even ROAS calculated?", a: "The simplified formula is 1 divided by gross margin expressed as a decimal. At a 40% margin, break-even ROAS is 1 / 0.40 = 2.5× before other variable costs." },
      { q: "Does this calculator upload campaign data?", a: "No. Values are calculated in your browser and are not sent to the site as tool input." },
    ],
  },
  {
    slug: "marketing-metrics-calculator",
    code: "MKT-02",
    category: "Marketing",
    title: "CPM, CPC, CTR & CPA Calculator",
    short: "Calculate the paid-media metrics that belong in one campaign view.",
    description: "Calculate CPM, CPC, CTR, conversion rate, CPA and ROAS from impressions, clicks, spend, conversions and revenue. Free browser-based marketing metrics calculator.",
    keywords: ["CPM calculator", "CPC calculator", "CTR calculator", "CPA calculator", "marketing metrics"],
    intro: "Paste the six numbers from an ad platform and get a consistent set of funnel metrics. Useful for QA, cross-platform reporting and spotting where performance changed.",
    steps: ["Enter impressions, clicks and spend.", "Optionally add conversions and revenue.", "Review traffic, conversion and revenue efficiency together."],
    notes: [
      "CPM measures cost per thousand impressions, CPC measures cost per click, and CTR measures the share of impressions that became clicks.",
      "CPA and conversion rate depend on what you count as a conversion. Keep that definition consistent across periods and platforms; otherwise the comparison is misleading even when the arithmetic is correct.",
    ],
    faq: [
      { q: "Can I leave conversions or revenue blank?", a: "Yes. Traffic metrics still calculate. Conversion and revenue metrics will display only when the required inputs are above zero." },
      { q: "Why does my platform show slightly different values?", a: "Platforms may round inputs, use modelled conversions, apply currency conversion or update attribution after the reporting window." },
      { q: "Are percentages entered as whole numbers?", a: "This tool derives percentages from counts, so enter raw impressions, clicks and conversions rather than pre-calculated rates." },
    ],
  },
  {
    slug: "profit-margin-calculator",
    code: "FIN-01",
    category: "Business",
    title: "Profit Margin Calculator",
    short: "Convert revenue and cost into profit and margin without spreadsheet setup.",
    description: "Free profit margin calculator. Calculate gross profit, profit margin and cost ratio from revenue and total cost, with a reverse price-from-margin mode.",
    keywords: ["profit margin calculator", "gross margin calculator", "calculate profit percentage", "margin formula"],
    intro: "Check the margin on a product, project or order. Use the standard mode for known revenue and cost, or reverse the calculation to find the selling price required for a target margin.",
    steps: ["Enter selling revenue and total cost.", "Read profit, margin and cost ratio.", "Use target margin mode when setting a selling price."],
    notes: [
      "Profit margin is profit divided by revenue. It answers: what share of the selling price remains after the costs included in this calculation?",
      "Decide which costs belong in the model before comparing products. A gross margin based only on product cost is not comparable with a contribution margin that also includes fulfilment, payment and advertising costs.",
    ],
    faq: [
      { q: "What is the difference between margin and markup?", a: "Margin divides profit by selling price. Markup divides profit by cost. The percentages are different even when cost and price are the same." },
      { q: "Can margin be negative?", a: "Yes. If cost is higher than revenue, profit and margin are negative." },
      { q: "Does this include tax?", a: "Only if the revenue and cost values you enter include tax. Use one consistent basis for both numbers." },
    ],
  },
  {
    slug: "markup-calculator",
    code: "FIN-02",
    category: "Business",
    title: "Markup Calculator",
    short: "Translate cost and selling price into markup, margin and gross profit.",
    description: "Free markup calculator for pricing products and services. Calculate markup percentage, margin, gross profit or selling price from cost and target markup.",
    keywords: ["markup calculator", "price markup calculator", "markup vs margin", "selling price calculator"],
    intro: "Price from cost without confusing markup and margin. The calculator shows both percentages side by side and can solve for selling price from a target markup.",
    steps: ["Enter unit cost and selling price.", "Compare markup with margin.", "Switch to target markup when testing a new price."],
    notes: [
      "Markup is profit divided by cost. If an item costs $80 and sells for $100, markup is 25% while margin is 20%.",
      "A target margin cannot be converted by simply adding that percentage to cost. For a 30% margin, selling price equals cost divided by 0.70.",
    ],
    faq: [
      { q: "Is 50% markup the same as 50% margin?", a: "No. A 50% markup on $100 cost gives a $150 price and a 33.3% margin. A 50% margin requires a $200 price." },
      { q: "Should shipping be included in cost?", a: "Include every variable cost you want the pricing decision to cover, such as inbound freight, packaging or transaction fees." },
      { q: "Can I use any currency?", a: "Yes. The formula is currency-neutral as long as cost and price use the same currency." },
    ],
  },
  {
    slug: "compound-interest-calculator",
    code: "FIN-03",
    category: "Finance",
    title: "Compound Interest Calculator",
    short: "Model a starting balance, monthly deposits and compounding over time.",
    description: "Free compound interest calculator with monthly contributions. Estimate future balance, total deposits and interest earned using monthly compounding.",
    keywords: ["compound interest calculator", "investment growth calculator", "monthly contribution calculator", "future value"],
    intro: "Estimate how a starting amount and repeated monthly contributions could grow at a constant annual rate. The result separates your deposits from calculated interest.",
    steps: ["Enter a starting balance and monthly contribution.", "Set an annual rate and time horizon.", "Compare total contributions with the projected ending balance."],
    notes: [
      "This model compounds monthly and assumes contributions are made at the end of each month. It uses a constant rate and does not model volatility, taxes, fees or inflation.",
      "The output is a mathematical scenario, not a forecast or investment recommendation. Real returns vary and can be negative.",
    ],
    faq: [
      { q: "What compounding frequency does this use?", a: "Monthly compounding with contributions added at the end of each month." },
      { q: "Is the annual rate guaranteed?", a: "No. It is an assumption for the calculation. Market, savings and lending rates can change." },
      { q: "Why is the result different from my bank?", a: "A bank may compound daily, apply tiered rates, round differently, charge fees or calculate contributions on different dates." },
    ],
  },
  {
    slug: "mortgage-payment-calculator",
    code: "FIN-04",
    category: "Finance",
    title: "Mortgage Payment Calculator",
    short: "Estimate principal-and-interest payments for a fixed-rate loan.",
    description: "Free fixed-rate mortgage calculator. Estimate monthly principal and interest, total payments and total interest from loan amount, rate and term.",
    keywords: ["mortgage calculator", "monthly mortgage payment", "home loan calculator", "loan amortization"],
    intro: "Estimate the principal-and-interest portion of a fixed-rate mortgage. Use the result as a planning baseline before adding taxes, insurance, fees and other ownership costs.",
    steps: ["Enter the loan amount after your down payment.", "Add the annual interest rate and loan term.", "Review monthly payment, total paid and total interest."],
    notes: [
      "The calculation uses the standard fixed-rate amortization formula and assumes equal monthly payments for the full term.",
      "It excludes property tax, insurance, association fees, lender fees, changing rates and early repayment. A lender quote and local disclosures control the actual payment.",
    ],
    faq: [
      { q: "Does this include property tax and insurance?", a: "No. It calculates principal and interest only." },
      { q: "Can I use it for an adjustable-rate mortgage?", a: "Only as a snapshot using one assumed rate. It does not model future rate adjustments." },
      { q: "Why might a lender show a different payment?", a: "Lenders may use different day-count rules, fees, insurance, escrow items and rounding." },
    ],
  },
  {
    slug: "business-days-calculator",
    code: "OPS-01",
    category: "Operations",
    title: "Business Days Calculator",
    short: "Count weekdays between dates or add working days to a start date.",
    description: "Free business days calculator. Count Monday-to-Friday weekdays between two dates or add working days to a start date in your browser.",
    keywords: ["business days calculator", "working days between dates", "add business days", "weekday calculator"],
    intro: "Count Monday-to-Friday working days or move a deadline forward by a set number of business days. The calculation stays deterministic and runs in your browser.",
    steps: ["Choose count-between or add-days mode.", "Enter the date range or start date and day count.", "Decide whether the start and end dates should be included."],
    notes: [
      "This tool treats Saturday and Sunday as non-working days. It does not automatically exclude national, regional or company holidays.",
      "Contract and shipping deadlines may use specific local definitions of a business day. Confirm the governing rule before relying on the result.",
    ],
    faq: [
      { q: "Are public holidays excluded?", a: "No. Holiday calendars differ by country, region and organization. Subtract applicable holidays separately." },
      { q: "Is the end date included?", a: "The calculator provides an include-end option so you can match your counting convention." },
      { q: "Does it handle negative day counts?", a: "Add-days mode supports moving backward when a negative number is entered." },
    ],
  },
  {
    slug: "csv-json-converter",
    code: "DEV-01",
    category: "Developer",
    title: "CSV ↔ JSON Converter",
    short: "Convert tabular CSV and JSON arrays locally without uploading data.",
    description: "Free CSV to JSON and JSON to CSV converter. Handles quoted commas and escaped quotes in your browser; copy or download the result without uploading input.",
    keywords: ["CSV to JSON", "JSON to CSV", "CSV converter", "online data converter"],
    intro: "Move a small dataset between CSV and JSON without setting up a script. The parser handles quoted fields, embedded commas and escaped double quotes.",
    steps: ["Choose CSV to JSON or JSON to CSV.", "Paste tabular input and convert.", "Check the preview, then copy or download the result."],
    notes: [
      "CSV has multiple dialects. This tool uses commas by default, the first row as headers, double quotes for escaped fields and UTF-8 text.",
      "JSON-to-CSV expects an array of flat objects. Nested objects are serialized as JSON strings so that no field is silently discarded.",
    ],
    faq: [
      { q: "Does it support commas inside a field?", a: "Yes, when the field is wrapped in double quotes. Escaped quotes use two consecutive double quotes." },
      { q: "Will numbers stay numbers?", a: "CSV has no native data types, so CSV-to-JSON values remain strings to avoid changing identifiers or leading zeros." },
      { q: "Is pasted data uploaded?", a: "No. Conversion happens in your browser." },
    ],
  },
  {
    slug: "image-compressor",
    code: "IMG-01",
    category: "Media",
    title: "Private Image Compressor",
    short: "Resize and compress JPEG, PNG or WebP images in the browser.",
    description: "Compress images privately in your browser. Set quality and maximum width, preview the result and download a smaller JPEG, PNG or WebP file without uploading it.",
    keywords: ["image compressor", "compress image online", "reduce image file size", "private image compression"],
    intro: "Reduce an image before uploading it to a website, form or marketplace. The browser decodes, resizes and exports the file locally; the selected image is not sent to this site as tool input.",
    steps: ["Choose a JPEG, PNG or WebP image.", "Set quality, output format and optional maximum width.", "Compare file size and download the compressed result."],
    notes: [
      "JPEG and WebP quality controls are lossy: lower values usually create smaller files with more visible artifacts. PNG output prioritizes transparency and may not shrink photographic images.",
      "Metadata such as camera information is not intentionally copied into the exported canvas image. Always inspect the downloaded file before deleting the original.",
    ],
    faq: [
      { q: "Does the image leave my device?", a: "No. The selected image is processed by browser APIs and is not uploaded as tool input." },
      { q: "Why is PNG still large?", a: "PNG is lossless and works best for graphics, text and transparency. Photos usually compress better as JPEG or WebP." },
      { q: "Can I enlarge an image?", a: "The maximum-width setting only reduces larger images; it does not upscale smaller images." },
    ],
  },
  {
    slug: "pdf-merger",
    code: "PDF-01",
    category: "Documents",
    title: "Private PDF Merger",
    short: "Combine multiple PDF files locally and download one document.",
    description: "Merge PDF files privately in your browser. Reorder selected documents, combine all pages and download one PDF without uploading the source files.",
    keywords: ["merge PDF", "combine PDF files", "private PDF merger", "PDF joiner"],
    intro: "Combine several PDFs into one file without sending documents to a conversion server. Arrange files in the required order, merge all pages and download the result.",
    steps: ["Select two or more PDF files.", "Move files up or down to set page order.", "Merge and download the combined PDF."],
    notes: [
      "All pages from each source file are copied in the displayed file order. Password-protected or damaged PDFs may not open.",
      "The merged file is created in browser memory. Very large documents can exceed the memory available on a phone or older computer; merge smaller batches if necessary.",
    ],
    faq: [
      { q: "Are PDFs uploaded?", a: "No. Files are read and merged locally in your browser." },
      { q: "Can I change the file order?", a: "Yes. Use the up and down controls before merging." },
      { q: "Does it preserve links and forms?", a: "Many page contents are preserved, but advanced forms, signatures, attachments or document-level features may not survive copying. Verify important files." },
    ],
  },
];

export const englishToolBySlug = Object.fromEntries(englishTools.map((tool) => [tool.slug, tool]));
